initial_bias: false
batch_norm: false
training:
  num_epochs: 80
  batch_size: 64
  bce_weight: 1
  augmentation: true

  optimizer:
    type: adam

    adam:
      lr: 1e-4
      weight_decay: 1e-2

    sgd:
      lr: 1e-2
      momentum: 0.9